config/routes.rb
Rails.application.routes.draw do
   root to: 'pages#home'
 # resources :savings
  devise_for :users
  
resources :users do
    resource :savings
  end

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/saving.rb
class Saving < ApplicationRecord
        validates :week, presence: true
        validates :amount, presence: true
    belongs_to :user
    
end

app/controllers/savings_controller.rb
class SavingsController < ApplicationController
  before_action :set_saving, only: [:show, :edit, :update, :destroy]

  # GET /savings
  # GET /savings.json
  def index
    @savings = Saving.all
  end

  # GET /savings/1
  # GET /savings/1.json
def show
  # Find the goal value out of the DB and then split it up over 27 weeks
  start_date = User.where(id: params[:user_id]).pluck(:start_date)
  end_date = User.where(id: params[:user_id]).pluck(:end_date)
  goal = User.where(id: params[:user_id]).pluck(:goal)
  
  goal_array = Array.new(2){Array.new(2)}
  goal_array[0][0]= start_date.last
  goal_array[1][0]= end_date.last
  goal_array[0][1] = 0
  goal_array[1][1] = goal.last
  
  @goal_array = goal_array
  # Find the saving data from the DB and associated week value, sort ASC
  data = Saving.where(user_id: params[:user_id]).pluck(:week,:amount)
  @data_sorted = data.sort {|x,y| x[0] <=> y[0] }
  
  # Cumulative sum of values - running total
  for i in 1..@data_sorted.length-1
    var1= @data_sorted[i][1]
    var2= @data_sorted[i-1][1]
    @data_sorted[i][1] = var1 + var2
  end
  

  #convert the string to UTC in milliseconds as per Java requirements
  for i in 0..@data_sorted.length-1
    @data_sorted[i][0] = Time.parse(@data_sorted[i][0]).utc.to_i*1000
  end

  for i in 0..goal_array.length-1
    goal_array[i][0] = Time.parse(goal_array[i][0]).utc.to_i*1000
  end
  

  date = Date.today.to_s
  current_date = Time.parse(date).utc.to_i*1000
  
  # Prepare highcharts with data from database
  @chart = LazyHighCharts::HighChart.new('graph') do |f|
  f.title({:text=>"Savings Progress"})
  
  f.yAxis [{
    title: {text: "Money Saved ($)" },
    
    min:0,
  }]
 
    f.xAxis [{
      type: 'datetime',
       #tickInterval: 5*7*24 * 3600 * 1000,
       

    plotLines: [{
        color: '#FF0000',
        width: 1,
        value: [current_date],
      
    }]

                     
    }]



#    f.xAxis(type: 'datetime', 
 # dateTimeLabelFormats: {second: '%l:%M:%S %p',
  #                   minute: '%l:%M %p', 
   #                  hour: '%l:%M %p',
    #                 day: '%e. %b', week: '%e. %b', 
     #                month: '%b \'%y', year: '%Y'})
                     
 # f.labels(:items=>[:html=>"Today's date in red", :style=>{:left=>"10px", :top=>"8px", :color=>"black"} ])      
  
  f.series(:type=> 'line',:name=> 'Savings to Date', :data=> @data_sorted)
  f.series(:type=> 'spline',:name=> 'Goal Savings', :data=> goal_array)
  f.series(:type=> 'line',:name=> 'Todays Date', :color=> 'red', :showSymbol=> 'false', :data=> 0)
  end
end 




# GET /savings/new
def new
  @saving = Saving.new
  end
  
  # GET /savings/1/edit
  def edit
  end
  
  # POST /savings
  # POST /savings.json
  def create
  
  
  @user = User.find( params[:user_id] )
  
  @saving = @user.saving.build( saving_params )
 
  respond_to do |format|
    if @saving.save
    format.html { redirect_to root_path, notice: 'Saving was successfully created.' }
    format.json { render :show, status: :created, location: @saving }
    else
    format.html { render :new }
    format.json { render json: @saving.errors, status: :unprocessable_entity }
  end
  end
end

# PATCH/PUT /savings/1
# PATCH/PUT /savings/1.json
def update
#respond_to do |format|
#if @saving.update(saving_params)
#  format.html { redirect_to @saving, notice: 'Saving was successfully updated.' }
#   format.json { render :show, status: :ok, location: @saving }
#  else
#   format.html { render :edit }
#    format.json { render json: @saving.errors, status: :unprocessable_entity }
#  end
#end
end

  # DELETE /savings/1
  # DELETE /savings/1.json
  def destroy
    #@saving.destroy
    #respond_to do |format|
     # format.html { redirect_to savings_url, notice: 'Saving was successfully destroyed.' }
    #  format.json { head :no_content }
    #end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_saving
    @user = User.find( params[:user_id] )
  
  end

    # Never trust parameters from the scary internet, only allow the white list through.
  def saving_params
   params.fetch(:saving, {}).permit(:week,:amount)
  end
end

app/helpers/savings_helper.rb
module SavingsHelper
end

app/views/savings/_form.html.erb
<div class ="container">
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <div class="well text-center">

        <div class ="text-center"><h2>Add Savings</h2></div>
        <%= form_for (saving), url: user_savings_path do |f| %>
        
          <% if saving.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(saving.errors.count, "error") %> prohibited this saving from being saved:</h2>
        
              <ul>
              <% saving.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            </div>
          <% end %>
        
        
          <div class="form-group">
            <%= f.label 'Entry Date' %>
            <%= f.date_field :week, autocomplete: "off", class: 'form-control' %>
            
            
          </div>
          <div class="form-group">
            <%= f.label 'Amount Saved' %>
            <%= f.text_field :amount, class: 'form-control' %>
          </div>
        
        
        
          <div class="actions">
            <%= f.submit %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/savings/edit.html.erb
<h1>Editing Saving</h1>

<%= render 'form', saving: @saving %>

<%= link_to 'Show', @saving %> |
<%= link_to 'Back', savings_path %>

app/views/savings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Savings</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @savings.each do |saving| %>
      <tr>
        <td><%= link_to 'Show', saving %></td>
        <td><%= link_to 'Edit', edit_saving_path(saving) %></td>
        <td><%= link_to 'Destroy', saving, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Saving', new_saving_path %>

app/views/savings/new.html.erb
<%= render 'form', saving: @saving %>

app/views/savings/show.html.erb
  
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <h1 class="title-text text-center">Your savings so far!</h1>
      <br>
      <h4 class="title-text">The below graph shows the hard work you have put in so far. </h4>
      <h4 class="title-text">Click on the blue savings line to get a detailed view of your savings contributions</h4>
<br>
      <div class="well">
        <p id="notice"><%= notice %></p>
        <%= high_chart("my_id4", @chart)  %>

      </div>     
    </div>   
  </div>
</div>