config/routes.rb
Rails.application.routes.draw do
   root to: 'pages#home'
 # resources :savings
  devise_for :users
  
resources :users do
    resource :savings
  end

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/pages/_new.html.erb
<div class ="title-text text-center"><h2>Log in</h2></div>

<div class ="container">
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <div class="well text-center">


        <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
          <div class="field">
            <%= f.label :email %><br />
            <%= f.email_field :email, autofocus: true %>
          </div>
        
          <div class="field">
            <%= f.label :password %><br />
            <%= f.password_field :password, autocomplete: "off" %>
          </div>
        
          <% if devise_mapping.rememberable? -%>
            <div class="field">
              <%= f.check_box :remember_me %>
              <%= f.label :remember_me %>
            </div>
          <% end -%>
        
          <div class="actions">
            <%= f.submit "Log in" %>
          </div>
        <% end %>
        
        <%= render "devise/shared/links" %>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<% if user_signed_in? %>

<div class="container">
  <div class ="row">
    <div class = "col-md-4 col-md-offset-4 text-center">
      <h1 class="title-text">Current Progress</h1>
      <br>
      <% if  !(Saving.where(user_id: current_user.id).count.zero?) %>
        <h2 class="title-text">You have saved $<%=@progress %> so far!</h2>
        <h2 class="title-text">That is <%=number_to_percentage(@percent, precision: 1) %> towards <%=@goal_title%>!</h2>
      <%else%>
        <h2 class="title-text">You haven't added any savings yet!</h2>
        <h2 class="title-text">Add some <%= link_to "here" , new_user_savings_path(user_id: current_user.id) %> </h2>
      <%end%>
<div id="content">

    <div id="thermo1" class="thermometer horizontal">

        <div class="track">
            <div class="goal">
                <div class="amount"><%= @goal_amount%></div>
            </div>
            <div class="progress">
                <div class="amount"><%= @progress%></div>
            </div>
        </div>

    </div>

</div>
    </div>
  </div>
</div>

<% else %>

<%= render "new" %>

<% end %>