config/routes.rb
Rails.application.routes.draw do
   root to: 'pages#home'
 # resources :savings
  devise_for :users
  
resources :users do
    resource :savings
  end

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Railsapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
   
  </head>

  <body>
    
    
  <body>
    <nav class="navbar navbar-default navbar-static-top" role="navigation">
      <div class='container'>
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
   
          <%= link_to root_path, class: "navbar-brand" do %>
            <i class="fa fa-group"></i>
            Home
          <% end %>
        </div>
        <div class="collapse navbar-collapse" id="main-nav-collapse">
          <div class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
            <ul>
             <%= link_to "Add New" , new_user_savings_path(user_id: current_user.id), class: 'btn btn-default navbar-btn'%>
             
              <% if  !(Saving.where(user_id: current_user.id).count.zero?) %>
            
             <%=link_to "View Savings" , user_savings_path(user_id: current_user.id), class: 'btn btn-default navbar-btn'%> 
             <% else%>
              <% end %>
              <%=link_to "Log Out", destroy_user_session_path, method: :delete, class:"btn btn-default navbar-btn" %>
              </ul>
            <% else%>
            <ul>
              <%= link_to "Log In", new_user_session_path, class: "btn btn-default navbar-btn" %>
              <%= link_to "Sign up", new_user_registration_path, class: 'btn btn-default navbar-btn'%>
            </ul>
            <% end %>
            
             
          </div>


        </div><!-- /.navbar-collapse -->
      </div>
    </nav>
    
      <div class="container flash-container">
        <% flash.each do |type, msg| %>
        <%= content_tag :div, msg, class:"alert alert-#{type}" %>
        <% end %>
      </div>
    
    
    
    <%= yield %>
  </body>
</html>